version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  build:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.4.6
      rails_version:
        type: string
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout
      - run:
          name: Check for 'master' branch
          command: |
              git fetch --all --quiet --prune --prune-tags
              if [[ -n "$(git branch --all --list master */master)" ]]; then
                  echo "A branch named 'master' was found. Please remove it."
                  echo "$(git branch --all --list master */master)"
              fi
              [[ -z "$(git branch --all --list master */master)" ]]

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - run: bundle exec rake db:migrate db:test:prepare

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - build:
          name: ruby3-4_rails8-0
          ruby_version: 3.4.4
          rails_version: 8.0.2
      - build:
          name: ruby3-3_rails7-2
          ruby_version: 3.3.4
          rails_version: 7.2.1
      - build:
          name: ruby3-2_rails7-2
          ruby_version: 3.2.5
          rails_version: 7.2.1
      - build:
          name: ruby3-1_rails7-2
          ruby_version: 3.1.3
          rails_version: 7.2.1
      - build:
          name: ruby3-3_rails7-1
          ruby_version: 3.3.4
          rails_version: 7.1.3.4
      - build:
          name: ruby3-2_rails7-1
          ruby_version: 3.2.5
          rails_version: 7.1.3.4
      - build:
          name: ruby3-1_rails7-1
          ruby_version: 3.1.3
          rails_version: 7.1.3.4
      - build:
          name: ruby3-2_rails7-0
          ruby_version: 3.2.0
          rails_version: 7.0.4.2
      - build:
          name: ruby3-1_rails7-0
          ruby_version: 3.1.3
          rails_version: 7.0.4.2
      - build:
          name: ruby3-0_rails7-0
          ruby_version: 3.0.5
          rails_version: 7.0.4.2
      - build:
          name: ruby3-2_rails6-1
          ruby_version: 3.2.0
          rails_version: 6.1.7.2
      - build:
          name: ruby3-1_rails6-1
          ruby_version: 3.1.3
          rails_version: 6.1.7.2
      - build:
          name: ruby3-0_rails6-1
          ruby_version: 3.0.5
          rails_version: 6.1.7.2
